deploy on prod

diff --git a/.github/workflows/bookden-ci-cd.yaml b/.github/workflows/bookden-ci-cd.yaml
--- a/.github/workflows/bookden-ci-cd.yaml
+++ b/.github/workflows/bookden-ci-cd.yaml
@@ -132,3 +132,73 @@ jobs:
         if: always()
         run: docker compose -f docker-compose.dev.yml down
         
+
+  deploy:
+    name: Deploy to Production
+    runs-on: ubuntu-24.04
+    needs: lint_and_test
+    if: github.ref == 'refs/heads/production' # Deploy to production if the branch is production
+
+    steps:
+
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0   # required for tagging
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}
+
+
+      - name: Build & Push SERVER image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile.server.prod
+          push: true
+          tags: |
+            imranpavel/bookden-server:latest
+
+        
+      - name: Build & Push CLIENT image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile.client.prod
+          push: true
+          tags: |
+            imranpavel/bookden-client:latest
+
+
+      - name: Deploy to Droplet
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.DROPLET_IP }}
+          username: root
+          key: ${{ secrets.DROPLET_SSH_KEY }}
+
+          # set -e -> If ANY command fails (exit code ≠ 0), stop the script immediately.
+          script: |
+            set -e
+
+            cd /root/bookden
+
+            echo "Stopping existing containers..."
+            docker compose -f docker-compose.prod.yml down
+
+            echo "Starting new containers and pulling latest images..."
+            docker compose -f docker-compose.prod.yml up -d --pull always --force-recreate
+
+            echo "Running SAFE cleanup..."
+            docker container prune -f
+            docker image prune -f
+            docker network prune -f
+            docker builder prune -f
+
+            echo "Deployment complete!"
